apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-deployment
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: php-deployment
 minReplicas: 1
 maxReplicas: 5
 targetCPUUtilizationPercentage: 10
